name       : python-umalqurra
version    : 0.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/59/d7/d57cfbf2ef0fd5f79c94bb4cc1fdb9af49eba592556e4e6891e2d5522fba/umalqurra-0.2.tar.gz : 719f6a36f908ada1c29dae0d934dd0f1e1f6e3305784edbec23ad719397de678
license    : MIT
component  : programming.python
summary    : Python Umalqurra Calendar is an API which gives you the ability to convert Gregorian and Hijri calendar.
description: |
    Python Umalqurra Calender is an API that will give you the ability to convert Gregorian to Hijri and Hijri to Gregorian.
build      : |
    %python3_setup
install    : |
    %python3_install
