name       : python-dateparser
version    : 0.7.4
release    : 1
source     :
    - https://github.com/scrapinghub/dateparser/archive/v0.7.4.tar.gz : 22f260d0a7d6db7a00026396952594533c5e7c275ada01b83733c0a9935d8b2b
license    : BSD-3-Clause
component  : programming.python
summary    : Python parser for human readable dates
description: |
    Dateparser provides modules to easily parse localized dates in almost any string formats commonly found on web pages.
builddeps  :
    - python-jdatetime
    - python-umalqurra
    - ruamel_yaml
rundeps    :
    - python-dateutil
    - python-regex
    - python-tzlocal
build      : |
    %python3_setup
install    : |
    %python3_install